### ISSUE TITLE
Otel Integration Metrics with High Cardinality

### ISSUE THREAD

**Issue by qgervacio** [coralogix/telemetry-shippers#313]
Hi,

We're looking at `http_server_duration_ms_bucket`, `http_client_duration_ms_bucket`, and `latency_ms_bucket`. It seems that these metrics are not currently utilized by CRX's default features, including the k8s Dashboard. While these metrics are valuable, they come with high cardinality, resulting in significant units consumption as indicated in Metrics Usage. These three metrics consistently rank among the top consumers on a daily basis.

I'm aware that certain metrics are essential for the proper functioning of the user interface, such as those obtained from kube-state-metrics. However, could we please get a list of the metrics that are essential for the UI to function correctly, or perhaps a list of metrics that we can safely exclude or remove via chart values override?

Thank you.

**Comment by qgervacio** [comment]
for my temporary workaround, I remove spanmetrics from the trace pipeline

**Comment by qgervacio** [comment]
In our account, we noticed e2m `cx_service_catalog_duration` and I'm under the impression that the metrics produced by this e2m is utilised in APM screen?

**Comment by qgervacio** [comment]
Thank you. I think we can further utilise `cx_service_catalog_duration` in a way saving units by dropping unused histograms. For `spanmetrics` I have removed it in my service pipeline and set `spanmetrics.metrics_exporter: logging`. 

For `http_server_duration_ms_bucket` and `http_client_duration_ms_bucket` are still ingested. which receiver in otel-integration are these coming from and how can we exclude it? I have tried below however these buckets are still ingested.
```
...
processors:
  filter/exclude-noisy-metrics:
    metrics:
      exclude:
        match_type: strict
        metric_names:
        - http_server_duration_ms_bucket
        - http_client_duration_ms_bucket
...
service:
  pipelines:
    metrics:
      processors:
      - resource/metadata
      - k8sattributes
      - resourcedetection/env
      - resourcedetection/region
      - memory_limiter
      - batch
      - filter/exclude-noisy-metrics
...
```
